# This is a basic workflow to help you get started with Actions

name: Release

# Controls when the action will run. 
on: 
  workflow_dispatch:
    inputs:
      version:
        description: 'The version to be released'     
        required: true
        default: '1.0.0'
      tags:
        description: 'The version to be released'  
  

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  # This workflow contains a single job called "build"
  build:
    # The type of runner that the job will run on
    runs-on: ubuntu-latest

    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
      # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
      - uses: actions/checkout@v2

      - name: release-it
        uses: TheRealWaldo/release-it@v0.2.2
        with:
          json-opts: '{"dry-run": true, "version": ${{ github.event.inputs.version }}}'

      # Runs a single command using the runners shell
      - name: Sign the new release
        run: |
          export GRAFANA_API_KEY=${{ secrets.GRAFANA_API_KEY }}
          npx @grafana/toolkit plugin:sign

          
